let products = [
    {
        "id":1,
        "image":"img/apricot.jpg",
        "caption":"Apricot",
        "price":"3$",
    },
    {
        "id":2,
        "image":"img/carrot.jpg",
        "caption":"Carrot",
        "price":"2$",
    },
    {
        "id":3,
        "image":"img/feta_cheese.jpg",
        "caption":"Feta cheese",
        "price":"12$",
    },
    {
        "id":4,
        "image":"img/lettuce.jpg",
        "caption":"Lettuce",
        "price":"1$",
    },
    {
        "id":5,
        "image":"img/olive_oil.jpg",
        "caption":"Olive oil",
        "price":"7$",
    },
    {
        "id":6,
        "image":"img/apple.jpg",
        "caption":"Apple",
        "price":"2$",
    },
    {
        "id":7,
        "image":"img/dried_bananas.jpg",
        "caption":"Dried bananas",
        "price":"7$",
    },
    {
        "id":8,
        "image":"img/ice_cream.jpg",
        "caption":"Ice cream",
        "price":"7$",
    },
    {
        "id":9,
        "image":"img/beetroot.jpg",
        "caption":"Beetroot",
        "price":"7$",
    },
    {
        "id":10,
        "image":"img/prune.jpg",
        "caption":"Prune",
        "price":"3$",
    },
    {
        "id":11,
        "image":"img/cabbage.jpg",
        "caption":"Cabbage",
        "price":"2$",
    },
    {
        "id":12,
        "image":"img/peanut_oil.jpg",
        "caption":"Peanut_oil",
        "price":"7$",
    },
    {
        "id":13,
        "image":"img/sour_cream.jpg",
        "caption":"Sour cream",
        "price":"3$",
    },
    {
        "id":14,
        "image":"img/mango.jpg",
        "caption":"Mango",
        "price":"5$",
    },
    {
        "id":15,
        "image":"img/lemon.jpg",
        "caption":"Lemon",
        "price":"3$",
    }

]